### ISSUE TITLE
Implement parser

### ISSUE THREAD

**Issue by DavidLeoni** [WikimediaSwitzerland/wiki2map#1]
We need to parse custom Vikidia and Wikiversity stuff - for details, see [wiki](https://github.com/WikimediaSwitzerland/wiki2map/wiki/Oggetti-che-il-parser-deve-riconoscere) . To do so, we will use [wtf_wikipedia](https://github.com/spencermountain/wtf_wikipedia) parser (see [wtf notes](https://github.com/WikimediaSwitzerland/wiki2map/wiki/wtf-parser)). Don't be fooled by the silly name,  looks like a good parser:

- works both in NodeJS and browser
- according to the author creates proper json structure, while Parsoid doesn't

For the records, I put here other alternatives we discarded:

*[parsoid](https://www.mediawiki.org/wiki/Parsoid)* 

- parser used for Visual editor of Wikimedia
- works in NodeJS
- TODO does it work in browser?
- mainly parses to HTML

*[RemexHTML](https://www.mediawiki.org/wiki/Parsing/Replacing_Tidy)*

- new official PHP  parser, replaces old one called Tidy

Maybe we could use WTF to get structured json so to have an easy structure for mindmaps , while we could use Parsoid for creating HTML to display in tooltips

**Comment by hbar-boi** [comment]
wtf_wikipedia sounds good!
