### ISSUE TITLE
Implement basic UI

### ISSUE THREAD

**Issue by DavidLeoni** [WikimediaSwitzerland/wiki2map#2]
[Mindmup Mapjs](https://github.com/mindmup/mapjs) looks like a good toolkit to start from.

See [Graphic engines](https://github.com/WikimediaSwitzerland/wiki2map/wiki/Graphic-engines) wiki page for discussion.

**Comment by hbar-boi** [comment]
I've taken a look at Mindmup and while it looks great it has many dependencies that I don't think we want to include if we want this to work smoothly on school pcs... I've started developing using [jsMind](https://github.com/hizzgdev/jsmind), very compact, lightweight and customizable!

**Comment by DavidLeoni** [comment]
I'm worried that the author writes issues in chinese so if you run into problems you might have trouble with debugging.

You should check the following is working or might work without too much tinkering :

* images: already supported
* html links ?
* arbitrary html ?
* videos ?
* what happens with large nodes? 
    * Can you impose a size limit ?
    * content in nodes can be dynamically expanded by user ?

**Comment by hbar-boi** [comment]
The library allows for complete customization of the mindmap, even more than we'd need... I already tried making something with it and it works great. You can add arbitrary html for each node, take a look at his demo [page](http://hizzgdev.github.io/jsmind/example/2_features.html)
